[project]
name = "antcolonyoptimization"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "manim>=0.19.0",
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "pyqt5>=5.15.11",
]
